
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/vismayb/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.0.0 - x86_64
...
